services:
  tmdb-radarr-digital:
    <<: *common-config
    image: docker.io/<dockerhub-username>/movie-star:latest
    container_name: tmdb-radarr-digital
    env_file:
      - /volume2/docker/movie-star/.env
