services:
  tmdb-radarr-digital:
    <<: *common-config
    build:
      context: /volume2/docker/movie-star
      dockerfile: Dockerfile
    image: local/tmdb-radarr-digital:latest
    container_name: tmdb-radarr-digital
    env_file:
      - /volume2/docker/movie-star/.env
